spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web_app
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: sql
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace